apiVersion: apps/v1
kind: Deployment
metadata:
  name: javascript-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javascript-app
  template:
    metadata:
      labels:
        app: javascript-app
    spec:
      containers:
        - name: javascript-app
          image: aksregistry2.azurecr.io/javascript:1.0  # Pulls from ACR
          ports:
            - containerPort: 3000

