apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: javascriptdemo 
  labels:
    app: javascriptdemo
    tier: frontend
    kube-monkey/enabled: "enabled"              # Enable termination of this deployment
    kube-monkey/identifier: monkey-victim    # Custom name for our target
    kube-monkey/mtbf: "1"                       # Average number of days between targeting one of these pods
    kube-monkey/kill-mode: "fixed" # The killing method
    kube-monkey/kill-value: "1"

spec: 
  selector: 
    matchLabels: 
      app: javascriptdemo
  replicas: 5 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: javascriptdemo
        tier: frontend
        kube-monkey/enabled: "enabled"              # Enable termination of this deployment
        kube-monkey/identifier: monkey-victim
    spec: 
      containers: 
      - name: javascriptdemo 
        image: appimages
        ports: 
        - containerPort: 3000 
      imagePullSecrets:
        - name: secretsz
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: javascript-service 
spec: 
  selector: 
    app: javascriptdemo 
  ports: 
  - protocol: TCP 
    port: 3000 
    targetPort: 3000 
  type: LoadBalancer
