# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "dev" ]   
  pull_request:
    branches: [ "dev" ] 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Docker Setup
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry (ACR)
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login aksregistry2.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Docker Build and Tag
        run: |
          cd $GITHUB_WORKSPACE/javascript
          docker build -t javascript:1.0 .
          docker tag javascript:1.0 aksregistry2.azurecr.io/javascript:1.0

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'javascript:1.0'
          format: 'table'
          exit-code: 0  # Change from 1 to 0 to allow vulnerabilities
          severity: 'CRITICAL,HIGH'


      - name: Docker Push
        run: |
          docker push aksregistry2.azurecr.io/javascript:1.0
          
      - name: Run a multi-line script
        run: |
          echo "Docker image successfully built, scanned, and pushed to ACR!"
